# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95fb0a5d9db0cd32ed3b38e63e93c6c101a3c9cde65b8e46fc7f21337bb5d3dc045776e752f529b15adc576aa8fc166f114739bd82e2566be81f1ec9c119e1f7

test:
  secret_key_base: 954115a403e406ef34437ff234604aad07f4e60426bae4210b79c9e5bf8f014afdc7f0fd35ad9a045a956cf51f1b08a9bc0e395a12490c10c29ef31689f6320d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
